### ISSUE TITLE
Ask for use of package name in NPM

### ISSUE THREAD

**Issue by JonatanSalas** [joshf/ra-language-spanish#1]
HI! @joshf! Hope you're doing well! 

I want to ask you, if there's a chance for me to use the name `ra-language-spanish` in NPM?

My organization is owner of the [spanish translation lib](https://github.com/BlackBoxVision/ra-language-spanish) support for admin-on-rest, now called react-admin, and we've updated the translations to match with react-admin, but we have still the old name tied to admin-on-rest `aor-language-spanish`.

I would like to talk, and see if you're open to this. If not, there's no trouble! Thanks anyway!

**Comment by joshf** [comment]
No problem at all, I quickly made this package when there wasn't a translation available. I did not realise it was live on NPM

**Comment by JonatanSalas** [comment]
@joshf  what do you need from me to make the package transfer?

**Comment by joshf** [comment]
I just looked on npm

Is this the package? https://www.npmjs.com/package/ra-language-spanish

I never actually published to npm myself this is another repo

**Comment by JonatanSalas** [comment]
My bad!
